modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
mixinConfigs = ["jsg.mixins.json"]
[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   displayURL="https://justsgmod.eu"
   authors="${mod_authors}"
   description='''${mod_description}'''
   updateJSONURL="https://api.modrinth.com/updates/jsg/forge_updates.json"
[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="jsg_core"
   mandatory=true
   versionRange="${core_version_range}"
   ordering="AFTER"
   side="BOTH"
