name: Bug report
description: "Some kind of issue that does not result in a crash such as incorrect behaviour or forced disconnectes from a server"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened
      description: >
        Please describe the issue in as much detail as posible.
        Explain what happened.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What should have happened
      description: >
        Please describe what you belive should have happened.
        if possible should not be a simple "Not what did" style response
    validations:
      required: true

  - type: input
    attributes:
      label: Latest log
      description: >
        We need your latest log for additional information about why the bug may have occured.
        you can find this file in the \"`logs`\" folder within your minecraft profile named \"`latest.log`\"
        Please upload the file to https://mclo.gs/ and put the link here.
        Do **NOT** paste the *contents* of the file here, doing so will make it very difficult to read and diagnose this issue.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Occurs in clean environment
      description: >
        Does the bug still occur when only JSG is present
      options:
        - label: Yes
        - label: No
        - label: Unknown
    validations:
      required: true

  - type: input
    attributes:
      label: JSG Version
      description: >
        Please provide the version of JSG you are using as the full name of the mod jar file located in your \"`mods`\" folder
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Thank you for taking the time to report this bug to help improve JSG"

