blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://discord.justsgmod.eu
    about: Join our discord and ask teh community.
  - name: Feature/Enhancment Suggestion
    url: https://discord.justsgmod.eu
    about: Suggest new features or improvments on our discord.
