package dev.tauri.jsg.config.stargate;

import dev.tauri.jsg.stargate.rig.RIGEntity;
import dev.tauri.jsg.stargate.rig.RIGWave;
import net.minecraft.Util;
import net.minecraft.world.Difficulty;

import java.util.HashMap;
import java.util.List;
import java.util.Map;


// TODO: Refactor waves ids
public class StargateRIGConfig {
    public static final Map<String, RIGWave> DEFAULT_VALUES = Util.make(new HashMap<>(), (map) -> {
        map.put("standard_hostile_wave", RIGWave.Builder.create()
                .weight(40)
                .addEntity(new RIGEntity("minecraft:zombie", 10, "{CanPickUpLoot:1b,CanBreakDoors:1b,ArmorItems:[{},{},{},{Count:1,id:leather_helmet,tag:{Enchantments:[{id:protection,lvl:2}]}}],ArmorDropChances:[0.0f,0.0f,0.0f,0.2f]}"))
                .addEntity(new RIGEntity("minecraft:zombie", 10, "{CanBreakDoors:1b,HandItems:[{Count:1,id:stone_sword},{}],ArmorItems:[{},{},{},{Count:1,id:iron_helmet}]}"))
                .addEntity(new RIGEntity("minecraft:zombie", 10, "{CanPickUpLoot:1b,ArmorItems:[{},{Count:1,id:leather_leggings},{},{Count:1,id:leather_helmet}],ArmorDropChances:[0.0f,0.3f,0.0f,0.2f]}"))
                .addEntity(new RIGEntity("minecraft:zombie", 7, "{IsBaby:1,CanPickUpLoot:1b,ArmorItems:[{},{},{},{Count:1,id:leather_helmet}],ArmorDropChances:[0.0f,0.0f,0.0f,0.2f]}"))
                .addEntity(new RIGEntity("minecraft:chicken", 1, "{Passengers:[{id:zombie,IsBaby:1,HandItems:[{Count:1,id:stone_sword,tag:{Enchantments:[{id:sharpness,lvl:1}]}},{}],ArmorItems:[{},{},{},{Count:1,id:golden_helmet,tag:{Enchantments:[{id:projectile_protection,lvl:2}]}}]}]}"))
                .blacklistedBiomes(List.of("#minecraft:is_nether", "#minecraft:is_end", "#forge:is_sandy", "#forge:is_cold/overworld", "#minecraft:is_ocean"))
                .selectRandomMobs()
                .randomMobsCount(5, 15)
                .build());
        map.put("Desert_hostile_wave", RIGWave.Builder.create()
                .weight(40)
                .addEntity(new RIGEntity("minecraft:husk", 30))
                .addEntity(new RIGEntity("minecraft:skeleton", 25, "{HandItems:[{Count:1,id:bow},{}], ArmorItems:[{},{},{},{Count:1, id:golden_helmet}], ArmorDropChances:[0.0f,0.0f,0.0f,0.1f]}"))
                .addEntity(new RIGEntity("minecraft:skeleton", 25, "{HandItems:[{Count:1,id:bow},{}], ArmorItems:[{},{},{},{Count:1, id:leather_helmet}], ArmorDropChances:[0.0f,0.0f,0.0f,0.4f]}"))
                .addEntity(new RIGEntity("minecraft:spider", 10))
                .allowedBiomes(List.of("#forge:is_sandy"))
                .selectRandomMobs()
                .randomMobsCount(5, 20)
                .build());
        map.put("Snowy_hostile_wave", RIGWave.Builder.create()
                .weight(40)
                .addEntity(new RIGEntity("minecraft:stray", 25, "{HandItems:[{Count:1,id:bow},{}],ArmorItems:[{},{},{},{Count:1,id:leather_helmet,tag:{display:{color:16383998}}}],HandDropChances:[0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:stray", 15, "{HandItems:[{Count:1,id:bow,tag:{Enchantments:[{id:power,lvl:1},{id:punch,lvl:1}]}},{}],ArmorItems:[{},{},{},{Count:1,id:leather_helmet,tag:{display:{color:16383998}}}]}"))
                .addEntity(new RIGEntity("minecraft:skeleton", 25, "{HandItems:[{Count:1,id:bow},{}], ArmorItems:[{},{},{},{Count:1, id:leather_helmet}], ArmorDropChances:[0.0f,0.0f,0.0f,0.3f]}"))
                .addEntity(new RIGEntity("minecraft:skeleton", 15, "{HandItems:[{Count:1,id:bow},{}], ArmorItems:[{},{},{},{Count:1, id:iron_helmet}], ArmorDropChances:[0.0f,0.0f,0.0f,0.1f]}"))
                .addEntity(new RIGEntity("minecraft:zombie", 10, "{CanPickUpLoot:1b,CanBreakDoors:1b,ArmorItems:[{},{},{},{Count:1,id:leather_helmet}]}"))
                .allowedBiomes(List.of("#forge:is_cold/overworld"))
                .selectRandomMobs()
                .randomMobsCount(5, 10)
                .build());
        map.put("Swamp_hostile_wave", RIGWave.Builder.create()
                .weight(40)
                .addEntity(new RIGEntity("minecraft:zombie", 10, "{CanPickUpLoot:1b,ArmorItems:[{},{Count:1,id:leather_leggings},{},{Count:1,id:leather_helmet}],ArmorDropChances:[0.0f,0.3f,0.0f,0.2f]}"))
                .addEntity(new RIGEntity("minecraft:skeleton", 10, "{HandItems:[{Count:1,id:bow},{}], ArmorItems:[{},{},{},{Count:1, id:iron_helmet}], ArmorDropChances:[0.0f,0.0f,0.0f,0.1f]}"))
                .addEntity(new RIGEntity("minecraft:creeper", 3))
                .addEntity(new RIGEntity("minecraft:witch", 1))
                .addEntity(new RIGEntity("minecraft:spider", 7))
                .addEntity(new RIGEntity("minecraft:spider", 1, "{Passengers:[{id:skeleton,HandItems:[{Count:1,id:bow},{}],ArmorItems:[{},{},{},{Count:1,id:chainmail_helmet,tag:{Enchantments:[{id:thorns,lvl:1}]}}]}]}"))
                .addEntity(new RIGEntity("minecraft:slime", 4))
                .allowedBiomes(List.of("#forge:is_swamp"))
                .selectRandomMobs()
                .randomMobsCount(2, 7)
                .build());
        map.put("Jungle_hostile_wave", RIGWave.Builder.create()
                .weight(40)
                .addEntity(new RIGEntity("minecraft:zombie", 5, "{CanPickUpLoot:1b,ArmorItems:[{},{Count:1,id:leather_leggings},{},{Count:1,id:leather_helmet}],ArmorDropChances:[0.0f,0.3f,0.0f,0.2f]}"))
                .addEntity(new RIGEntity("minecraft:skeleton", 5, "{HandItems:[{Count:1,id:bow},{}], ArmorItems:[{},{},{},{Count:1, id:golden_helmet}]}"))
                .addEntity(new RIGEntity("minecraft:spider", 10))
                .addEntity(new RIGEntity("minecraft:spider", 1, "{Passengers:[{id:skeleton,HandItems:[{Count:1,id:bow},{}],ArmorItems:[{},{},{},{Count:1,id:chainmail_helmet,tag:{Enchantments:[{id:thorns,lvl:1}]}}]}]}"))
                .allowedBiomes(List.of("is_wet/overworld", "#minecraft:is_forest"))
                .selectRandomMobs()
                .randomMobsCount(2, 7)
                .build());
        map.put("Ocean_hostile_wave", RIGWave.Builder.create()
                .weight(8)
                .addEntity(new RIGEntity("minecraft:drowned", 15, "{CanBreakDoors:1b}"))
                .addEntity(new RIGEntity("minecraft:drowned", 8, "{HandItems:[{Count:1,id:trident},{}]}"))
                .addEntity(new RIGEntity("minecraft:drowned", 10, "{CanBreakDoors:1b, HandItems:[{Count:1,id:nautilus_shell},{}]}"))
                .addEntity(new RIGEntity("minecraft:guardian", 2))
                .allowedBiomes(List.of("#minecraft:is_ocean"))
                .selectRandomMobs()
                .randomMobsCount(4, 7)
                .build());
        map.put("NetherZombie_piglin_wave", RIGWave.Builder.create()
                .weight(17)
                .addEntity(new RIGEntity("minecraft:zombified_piglin", 10, "{CanBreakDoors:1b,HandItems:[{Count:1,id:golden_sword},{}]}"))
                .addEntity(new RIGEntity("minecraft:skeleton", 4, "{HandItems:[{Count:1,id:bow},{}]}"))
                .allowedBiomes(List.of("#minecraft:is_nether"))
                .selectRandomMobs()
                .randomMobsCount(3, 10)
                .build());
        map.put("NetherHunting_piglin_wave", RIGWave.Builder.create()
                .weight(12)
                .addEntity(new RIGEntity("minecraft:hoglin", 8, "{Age:-25000}"))
                .addEntity(new RIGEntity("minecraft:hoglin", 9))
                .addEntity(new RIGEntity("minecraft:piglin_brute", 10))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:crossbow},{}]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:crossbow},{}],ArmorItems:[{},{},{},{Count:1,id:golden_helmet}],ArmorDropChances:[0.0f,0.0f,0.0f,1.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:crossbow},{}],ArmorItems:[{Count:1,id:golden_boots},{Count:1,id:golden_leggings},{},{}],ArmorDropChances:[0.1f,0.1f,0.0f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:crossbow},{}],ArmorItems:[{},{},{Count:1,id:golden_chestplate},{}],ArmorDropChances:[0.0f,0.0f,0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:crossbow},{}],ArmorItems:[{Count:1,id:golden_boots},{},{Count:1,id:golden_chestplate},{Count:1,id:golden_helmet}],ArmorDropChances:[0.1f,0.1f,0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:crossbow},{}],ArmorItems:[{Count:1,id:golden_boots},{},{Count:1,id:golden_chestplate},{}],ArmorDropChances:[0.1f,0.0f,0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:golden_sword},{}]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:golden_sword},{}],ArmorItems:[{},{},{},{Count:1,id:golden_helmet}],ArmorDropChances:[0.0f,0.0f,0.0f,1.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:golden_sword},{}],ArmorItems:[{Count:1,id:golden_boots},{Count:1,id:golden_leggings},{},{}],ArmorDropChances:[0.1f,0.1f,0.0f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:golden_sword},{}],ArmorItems:[{},{},{Count:1,id:golden_chestplate},{}],ArmorDropChances:[0.0f,0.0f,0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:golden_sword},{}],ArmorItems:[{Count:1,id:golden_boots},{},{Count:1,id:golden_chestplate},{Count:1,id:golden_helmet}],ArmorDropChances:[0.1f,0.1f,0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:piglin", 19, "{HandItems:[{Count:1,id:golden_sword},{}],ArmorItems:[{Count:1,id:golden_boots},{},{Count:1,id:golden_chestplate},{}],ArmorDropChances:[0.1f,0.0f,0.1f,0.0f]}"))
                .allowedBiomes(List.of("#minecraft:is_nether"))
                .selectRandomMobs()
                .randomMobsCount(6, 12)
                .shouldOpenIrisChance(0.05)
                .build());
        map.put("NetherFortress_wave", RIGWave.Builder.create()
                .weight(8)
                .addEntity(new RIGEntity("minecraft:zombified_piglin", 12, "{CanBreakDoors:1b,HandItems:[{Count:1,id:golden_sword},{}]}"))
                .addEntity(new RIGEntity("minecraft:blaze", 4))
                .addEntity(new RIGEntity("wither_skeleton", 4, "{HandItems:[{Count:1,id:stone_sword},{}]}"))
                .allowedBiomes(List.of("#minecraft:is_nether"))
                .selectRandomMobs()
                .randomMobsCount(4, 12)
                .build());
        map.put("End_wave", RIGWave.Builder.create()
                .weight(5)
                .addEntity(new RIGEntity("minecraft:enderman", 1))
                .allowedBiomes(List.of("#minecraft:is_end"))
                .selectRandomMobs()
                .randomMobsCount(4, 9)
                .chevronsToDial(8)
                .build());
        map.put("Vindicators_wave", RIGWave.Builder.create()
                .weight(17)
                .addEntity(new RIGEntity("minecraft:vindicator", 40, "{HandItems:[{Count:1, id:iron_axe},{}],HandDropChances:[0.1f,0.0f]}"))
                .addEntity(new RIGEntity("minecraft:evoker", 1))
                .addEntity(new RIGEntity("minecraft:witch", 5))
                .addDifficulty(Difficulty.NORMAL, true)
                .addDifficulty(Difficulty.HARD)
                .allowedBiomes(List.of("#minecraft:is_overworld"))
                .blacklistedBiomes(List.of("#minecraft:is_ocean"))
                .selectRandomMobs()
                .randomMobsCount(10, 15)
                .shouldOpenIrisChance(0.05)
                .build());
        map.put("Warden_wave", RIGWave.Builder.create()
                .weight(1)
                .addEntity(new RIGEntity("minecraft:warden", 1, "{Brain:{memories:{\"minecraft:dig_cooldown\":{value:{},ttl:1200L}}}}"))
                .addDifficulty(Difficulty.HARD, true)
                .allowedBiomes(List.of("#minecraft:is_overworld"))
                .blacklistedBiomes(List.of("#micraft.is_ocean"))
                .build());
        map.put("VillagerPlains_wave", RIGWave.Builder.create()
                .weight(12)
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:farmer,level:1,type:plains}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:fisherman,level:1,type:plains}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:leatherworker,level:1,type:plains}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:armorer,level:1,type:plains}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 10, "{VillagerData:{profession:nitwit,level:1,type:plains}}"))
                .addEntity(new RIGEntity("minecraft:villager", 1, "{VillagerData:{profession:\"jsg:priest_plains\",level:1,type:plains}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 1, "{VillagerData:{profession:\"jsg:priest_jungle\",level:1,type:jungle}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:chicken", 1))
                .addDifficulty(Difficulty.PEACEFUL)
                .allowedBiomes(List.of("#minecraft:has_structure/village_plains", "#minecraft:has_structure/village_savanna"))
                .selectRandomMobs()
                .randomMobsCount(3, 6)
                .shouldOpenIrisChance(0.3)
                .build());
        map.put("VillagerDesert_wave", RIGWave.Builder.create()
                .weight(12)
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:cartographer,level:1,type:desert}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:librarian,level:1,type:desert}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:mason,level:1,type:desert}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:toolsmith,level:1,type:desert}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 10, "{VillagerData:{profession:nitwit,level:1,type:desert}}"))
                .addEntity(new RIGEntity("minecraft:villager", 10, "{VillagerData:{profession:\"jsg:priest_desert\",level:1,type:desert}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:rabbit", 1))
                .addDifficulty(Difficulty.PEACEFUL)
                .allowedBiomes(List.of("#minecraft:has_structure/village_desert", "#minecraft:has_structure/village_savanna"))
                .selectRandomMobs()
                .randomMobsCount(4, 8)
                .shouldOpenIrisChance(0.3)
                .build());
        map.put("VillagerSavanna_wave", RIGWave.Builder.create()
                .weight(12)
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:cartographer,level:1,type:savanna}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:cleric,level:1,type:savanna}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:leatherworker,level:1,type:savanna}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:butcher,level:1,type:savanna}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 10, "{VillagerData:{profession:nitwit,level:1,type:savanna}}"))
                .addEntity(new RIGEntity("minecraft:villager", 1, "{VillagerData:{profession:\"jsg:priest_savanna\",level:1,type:savanna}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 1, "{VillagerData:{profession:\"jsg:priest_swamp\",level:1,type:swamp}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:cat", 1, "{variant:red}"))
                .addEntity(new RIGEntity("minecraft:sheep", 1))
                .addDifficulty(Difficulty.PEACEFUL)
                .allowedBiomes(List.of("#minecraft:has_structure/village_savanna", "#minecraft:has_structure/village_plains", "#minecraft:has_structure/village_desert"))
                .selectRandomMobs()
                .randomMobsCount(3, 8)
                .shouldOpenIrisChance(0.3)
                .build());
        map.put("VillagerSnowy_wave", RIGWave.Builder.create()
                .weight(12)
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:farmer,level:1,type:snow}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:armorer,level:1,type:snow}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:librarian,level:1,type:snow}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 10, "{VillagerData:{profession:nitwit,level:1,type:snow}}"))
                .addEntity(new RIGEntity("minecraft:villager", 1, "{VillagerData:{profession:\"jsg:priest_snow\",level:1,type:snow}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:iron_golem", 1))
                .addDifficulty(Difficulty.PEACEFUL)
                .allowedBiomes(List.of("#minecraft:has_structure/village_snowy", "#minecraft:has_structure/village_taiga"))
                .selectRandomMobs()
                .randomMobsCount(2, 7)
                .shouldOpenIrisChance(0.3)
                .build());
        map.put("VillagerTaiga_wave", RIGWave.Builder.create()
                .weight(12)
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:fletcher,level:1,type:taiga}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:armorer,level:1,type:taiga}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:toolsmith,level:1,type:taiga}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:weaponsmith,level:1,type:taiga}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 5, "{VillagerData:{profession:leatherworker,level:1,type:taiga}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:villager", 10, "{VillagerData:{profession:nitwit,level:1,type:taiga}}"))
                .addEntity(new RIGEntity("minecraft:villager", 1, "{VillagerData:{profession:\"jsg:priest_taiga\",level:1,type:taiga}, Xp: 1}"))
                .addEntity(new RIGEntity("minecraft:pig", 1))
                .addDifficulty(Difficulty.PEACEFUL)
                .allowedBiomes(List.of("#minecraft:has_structure/village_taiga", "#minecraft:has_structure/village_snowy"))
                .selectRandomMobs()
                .randomMobsCount(4, 6)
                .shouldOpenIrisChance(0.3)
                .build());
        map.put("Trader_wave", RIGWave.Builder.create()
                .weight(5)
                .addEntity(new RIGEntity("minecraft:wandering_trader", 1, "{UUID:%UUID%,DespawnDelay:48000}"))
                .addEntity(new RIGEntity("minecraft:trader_llama", 2, "{Leashed:1b,Leash:{UUID:%UUID%}}"))
                .addDifficulty(Difficulty.PEACEFUL)
                .allowedBiomes(List.of("#minecraft:is_overworld"))
                .blacklistedBiomes(List.of("#minecraft:is_ocean"))
                .chevronsToDial(9)
                .build());
    });
}
